### PR TITLE
Added support to phone mask with country code

### PR DESCRIPTION
**Pull request by jbsathler**
Added support to phone numbers with country code, between available masks. i.e.:

+55 (11) 1234-5678
+55 (11) 9-1234-5678

### CODE REVIEW

**Comment by AlexandreBarroso** [comment]
format angular2-text-mask  Brasil ,  phone, cpf, rg,cnpj, cep.

**Comment by assisrafael** [comment]
Thank you for the pull request.
However it does not pass all tests. Can you fix this?

**Comment by assisrafael** [comment]
Fixed by #299

**Comment by FabioMorcillo** [comment]
How i can disable country code from ui-br-phone-number ?

Thank you,

**Pull request closed without merging**
