### PR TITLE
Add french phone number format

### PR DESCRIPTION
**Pull request by cdupoiron**

### CODE REVIEW

**Comment by assisrafael** [comment]
Your code need some adptation to be merged. Let me know when you are done.

**Comment by cdupoiron** [comment]
@assisrafael I tried to merge your last version. Tests don't pass, any clue?

**Comment by assisrafael** [comment]
From inspecting the code everything seems fine (with the exception of the src/masks.js and src/us/* files that should not be included in your PR).

**Comment by assisrafael** [comment]
Have you manage to fix the breaking tests?

**Comment by assisrafael** [comment]
Fixed by 6c1b45087c2757be8832acc7a86ff0c9c3816a45

**Pull request closed without merging**
