### PR TITLE
update to allow ui-money-mask to accept negative numbers

### PR DESCRIPTION
**Pull request by aktary**
Fixing my own problem here... please integrate it.

### CODE REVIEW

**Comment by aktary** [comment]
I'm not sure what's causing the build failure... but it was happening when I first branched before I made my changes...

**Comment by aktary** [comment]
Fixes #97  and #86

**Comment by assisrafael** [comment]
Please check the test results. Your patch breaks some tests.

**Comment by aktary** [comment]
Sorry man... but these tests were already failing before I got here.  I just did a fresh pull of your master and ran gulp test... and it failed.  Am I doing something wrong here?

**Comment by assisrafael** [comment]
According to travis-ci all commits in master since v1.5.2 are passing all the tests. Take a look: https://travis-ci.org/assisrafael/angular-input-masks/builds

**Comment by aktary** [comment]
This is so weird.  I have checked out exactly your latest commit to master #b1224a1 and it's failing a date test on my system: 

Chrome 44.0.2403 (Linux 0.0.0) ui-date-mask should format initial model values FAILED
	Expected '1999-12-30' to be '1999-12-31'.
	    at Object.<anonymous> (/tmp/5474234e26dc184071183300e02642e0.browserify:4814:28 <- src/global/date/date.test.js:29:0)
Chrome 44.0.2403 (Linux 0.0.0): Executed 91 of 91 (1 FAILED) (1.217 secs / 1.142 secs)

This is *without* my changes (which are on another branch).

**Comment by assisrafael** [comment]
What is your timezone?

**Comment by aktary** [comment]
Pacific Standard Time

**Comment by aktary** [comment]
Welp... I was having an issue pushing my local commit to my fork's master branch, so I couldn't update this PR and will therefore close it.  Since my commit only affected money.js and it's now passing all tests, I'm not going to worry about that date test failing...although it was weird.  I've opened a new PR and am closing this one.

**Pull request closed without merging**
