### PR TITLE
Updating Parser function of number.js to fix issue #147

### PR DESCRIPTION
**Pull request by PrateekRai**
Updating Parser function of number.js to fix issue #147

In a negative number scenario, I want to start by entering minus sign followed by number, but this is not working as on 1st minus sign, it shows 0 and then I have to enter some number after that only I can enter minus sign.

Another problem is, if negative number is in input field and if I want to make it positive by hitting minus sign then my cursor must be at the end, if it is at the start or in mid then it is not working.

### CODE REVIEW

**Comment by assisrafael** [comment]
Thank you for this pull request.
However there are some issues with the CI.
Please, take a look at the [CI output](https://travis-ci.org/assisrafael/angular-input-masks/builds/98569374).

**Comment by IsItBroken** [comment]
Could this just not easily be done by just altering the if statement of the original code to:

`if ((needsToInvertSign ^ isNegative) || value === '-') {
   actualNumber *= -1;
   formatedValue = '-' + formatedValue;
}`

**Comment by assisrafael** [comment]
@IsItBroken submit a pull request with your approach

**Comment by assisrafael** [comment]
Closing due to inactivity.

**Pull request closed without merging**
