### PR TITLE
add ui-br-placa-mask

### PR DESCRIPTION
**Pull request by dflourusso**
Placas de veículos

### CODE REVIEW

**Comment by assisrafael** [comment]
Thank you for you pull request.
However the CI is not green, so take a look at the TravisCI output, and as soon as it passes I can merge your work.

**Comment by dflourusso** [comment]
Thanks

**Comment by assisrafael** [comment]
Another suggestion: change the directive name from "placa" to "car-plate".

**Comment by dflourusso** [comment]
Hello, the changes were made, i'm waiting for the merge.

**Comment by assisrafael** [comment]
Nice. The last thing is:
- squash your commits into a single commit
- follow the angular commit convention, something like `feat(ui-br-placa-mask): input mask for brazilian car plate` (the changelog is autommatic generated from the commits)

**Comment by dflourusso** [comment]
Travis failed in a DateMask, but i didn't any change in DateMask.
My implementation is working fine.

**Comment by dflourusso** [comment]
Hello again, the release folder was in my *.gitignore*, could you generate a release with the *ui-br-car-plate-mask* please?
Thank's

**Pull request merged**
