### PR TITLE
Add the option to set the currency prefix.

### PR DESCRIPTION
**Pull request by picheli20**
Nowadays its not possible to make the configuration of the currency prefix. Will be nice to be able to setup, not just the default.

### CODE REVIEW

**Comment by assisrafael** [comment]
Thank you for the pull request.
Before merging, your code need to pass the CI.

**Comment by picheli20** [comment]
Sorry Rafael,
Here in my work i'm not able to test property the code. I think now its passing.

**Comment by picheli20** [comment]
I created the test but idk how to include on this issue.

This is the commit https://github.com/assisrafael/angular-input-masks/commit/073af5a5de60eaeaf9c11498578399172891f7a7

**Comment by assisrafael** [comment]
I don't kwow either. Try to redo the test commit into the pull request branch in your fork.

**Pull request closed without merging**
