### PR TITLE
feat(ui-percentage-value): add attribute ui-percentage-value 

### PR DESCRIPTION
**Pull request by dvbeato**
adding attribute ui-percentage-value to use $modelValue and $viewValue as the same

### CODE REVIEW

**Comment by dvbeato** [comment]
@assisrafael done.

**Comment by assisrafael** [comment]
Why did you close this PR?
The code seems fine.

**Comment by dvbeato** [comment]
it ins't work correctly, I found a bug in my code, I will fix and reopen the PR

**Comment by dvbeato** [comment]
@assisrafael done. I also add .editorconfig to help keep codestyle.

**Pull request merged**
