### PR TITLE
Fix validation issues on us phone number

### PR DESCRIPTION
**Pull request by houmark**
Very simple, but makes the directive useful for me.

### CODE REVIEW

**Comment by assisrafael** [comment]
Thank you for the pull request.
Can you implement a test case to cover this bug?

**Comment by houmark** [comment]
This one really is a one line no-brainer, but without this pulled the phone number cannot validate for me at all (when the phone number is just a number) which makes the entire module useless. I wonder how it stayed in so long? ;)

If you insist I will go it a go, but it will be some time before I can find time to do it.

**Comment by assisrafael** [comment]
Only a test case can prevent this feature to be accidentally removed in the future and break your code.

**Comment by houmark** [comment]
@assisrafael I finally had time to get back around to do the test you asked for. Hoping to see this merged soon.

**Pull request merged**
