### PR TITLE
Fixes bug watching min and max attributes on money mask

### PR DESCRIPTION
**Pull request by danielpamplona**
This bugs occurs when these attributes are changed dynamically .

### CODE REVIEW

**Comment by assisrafael** [comment]
Thank you for the pull request. Can you write a test case that exhibits this bug?

**Comment by danielpamplona** [comment]
I wasn't able to simulate this bug in tests :/ 

Can I simulate it in Fiddle then?

**Comment by assisrafael** [comment]
It is a start.

**Comment by julesce** [comment]
👍  and ➕ 1 for this pull request. I can confirm that it fixes the bug that I've been experiencing as well.

**Comment by assisrafael** [comment]
This PR will not be merged because the intended behavior is to use an expression not an interpolation: https://stackoverflow.com/questions/14876112/angularjs-difference-between-the-observe-and-watch-methods

**Pull request closed without merging**
