### PR TITLE
Inserção de Máscara do Tipo "Mês/Ano"

### PR DESCRIPTION
**Pull request by tiagoadp**
Inserção de Máscara do Tipo "Mês/Ano"

Insertion of "Month/Year" mask Type

### CODE REVIEW

**Comment by assisrafael** [comment]
Thank you for helping.
Since this is a very simple mask, It will be better if you use the (mask-factory)[https://github.com/assisrafael/angular-input-masks/blob/master/src/node_modules/mask-factory.js] (for example like in the (CEP mask)[https://github.com/assisrafael/angular-input-masks/blob/master/src/br/cep/cep.js].

If possible, include some test cases for your directive (take a look at the (date-mask)[https://github.com/assisrafael/angular-input-masks/blob/master/src/global/date/date.test.js] tests for example).

**Comment by tiagoadp** [comment]
I haven´t used mask-factory because i am validating if its an valid date, and if its an american date it will convert to YYYY-MM or in BR = MM/YYYY like you have done on DateMask...

And the result its a date with day 01 on month, like 1990-12-01 so you can save this on DB directly or get only the string if the user wants... I haven´t done a test case, but, its testes on my current development project... Because of that i created the mask and shared it... Maybe i will create a few more and i will share them too...

**Comment by assisrafael** [comment]
Have you managed to include tests?

**Comment by assisrafael** [comment]
Closing due to inactivity.

**Pull request closed without merging**
