### PR TITLE
Add mask for American Express cards

### PR DESCRIPTION
**Pull request by condereis**

### CODE REVIEW

**Comment by assisrafael** [comment]
@condereis can you provide tests for the changes you are proposing?

**Comment by condereis** [comment]
@assisrafael Is that enough?

**Comment by assisrafael** [comment]
Can you merge from master? I just included github actions on it.

**Comment by condereis** [comment]
I am not quite sure what you're asking. I have already merged from master.

**Comment by assisrafael** [comment]
@condereis your PR need to have this commit https://github.com/assisrafael/angular-input-masks/commit/2b81b477b5b8f26cdf791020c19714084e1f2c94

**Comment by assisrafael** [comment]
Closing this PR because of outdated content.

**Pull request closed without merging**
