### PR TITLE
Initial 0 on percentage not formatted

### PR DESCRIPTION
**Pull request by faelcorreia**
Issue #52

### CODE REVIEW

**Comment by assisrafael** [comment]
I had tested your patch and found that your test pass even if your bug fix is not used.
The problem is with your model value: ```'0'```
In JavaScript ```!'0' === false``` so this case is covered.
However, if you change your model value to ```0``` the directive throws an error.
The main problem is that the formatter needs to convert the number to string before trying to format it.

**Comment by assisrafael** [comment]
Take a look at the tests that I included into the develop branch: 55e1eb2af20bc92f5725f53b025316ac4fe9b859

**Comment by faelcorreia** [comment]
I see. Would be right to call toString on value before return it?

**Comment by assisrafael** [comment]
You had tried it?

**Comment by assisrafael** [comment]
Fixed in 5d0f456b2a63e64ec406c009b2628a61bee1b094

**Pull request closed without merging**
