### PR TITLE
Allow ui-negative-number in ui-percentage-mask

### PR DESCRIPTION
**Pull request by Konageski**
In percentage mask, analise the tag ui-negative-number e correct value
and mask

### CODE REVIEW

**Comment by assisrafael** [comment]
I'm not sure about this change.
Can you implement a test case that shows the behavior you need?

**Comment by Konageski** [comment]
Today is not possible to use negative number in percentage-mask field.
This change able to use **ui-negative-number** in ui-percentage-mask field.
I use this change in my system.

`<input type="text" name="negativePercentage" ng-model="obj.negativePercentage" class="form-control"  ui-percentage-mask="2" **ui-negative-number** required>
`
image

**Comment by guylhermetabosa** [comment]
+1

**Comment by guylhermetabosa** [comment]
This definitely should be available in this lib. Thanks @Konageski.

**Comment by assisrafael** [comment]
Replaced by #300

**Pull request closed without merging**
