### PR TITLE
fixes #180

### LINKED ISSUE #180: ui-money breaks if decimals are defined as a string
Hi there. 

`ui-money-type` breaks if decimals are defined as a string. 

Example code: 
```
<input ng-model="money" ui-money-mask="decimals" placeholder="Money" ng-init="money = 15.55">
<input type="text" ng-model="decimals" ng-init="decimals = 2" placeholder="Money decimals">
```
The problem seems to be at this line: https://github.com/assisrafael/angular-input-masks/blob/master/src/global/money/money.js#L17. The function `isNaN` returns `false` if the value is a "number" string (ex: `"1"`). When  creating a `new Array`, instead of creating a array with decimals plus 1 positions, it creates an array with one position with a concatenation between the decimals and 1 (ex: `new Array("31")`).

A suggestion is use `parseInt()` before it creates a new Array, allowing string as definition of decimals.

I tested with `percentage-mask` and `number-mask` and this problem doesn't happen. 

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/33304335-ui-money-breaks-if-decimals-are-defined-as-a-string?utm_campaign=plugin&utm_content=tracker%2F1022469&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1022469&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by marcomafessolli**
Allows decimals as string at MoneyMask

### CODE REVIEW

**Comment by assisrafael** [comment]
Thank you for your pull request. Could you write a test case to cover this feature?

**Comment by marcomafessolli** [comment]
@assisrafael I could remove `ui-number-mask=0` at `number.html` which is parsing the string value to int, or create a new html block with a new decimals input without `ui-number-mask` and create a new test for it. 

Which one do you prefere?

**Comment by assisrafael** [comment]
You can implement a new unit test case here: https://github.com/assisrafael/angular-input-masks/blob/master/src/global/number/number.test.js

**Comment by marcomafessolli** [comment]
@assisrafael I've wrote a test that covers string as definition of decimals but at `money.spec.js` as it was a bug that only happens at `ui-money-mask`. 

Let me know what you think

**Comment by assisrafael** [comment]
I see. The best place will be: https://github.com/assisrafael/angular-input-masks/blob/master/src/global/money/money.test.js as this feature does not need an e2e test (like those in money.spec.js).

**Comment by marcomafessolli** [comment]
@assisrafael tests moved.

Could you review?

**Comment by assisrafael** [comment]
Thank you!

**Pull request merged**
