### PR TITLE
Allow minus sign as first character for negative numbers

### LINKED ISSUE #147: Minus sign is not allowed as 1st character & pressing minus doesn't negate if cursor is not at the end
Hi,

In a negative number scenario, I want to start by entering minus sign followed by number, but this is not working as on 1st minus sign, it shows 0 and then I have to enter some number after that only I can enter minus sign.

Another problem is, if negative number is in input field and if I want to make it positive by hitting minus sign then my cursor must be at the end, if it is at the start or in mid then it is not working.

Please let me know if there is any workaround to handle this scenario.  

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/29365843-minus-sign-is-not-allowed-as-1st-character-pressing-minus-doesn-t-negate-if-cursor-is-not-at-the-end?utm_campaign=plugin&utm_content=tracker%2F1022469&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1022469&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by brunobastosg**
Fixes #147.

Based on @IsItBroken 's suggestion in PR #149.

### CODE REVIEW

**Comment by assisrafael** [comment]
Thank you for the pull request.
Can you implement a test case for this behaviour?

**Comment by brunobastosg** [comment]
I started implementing a test case for this but I found some problems with it.

If I leave the code as it is, the component will allow -0 (which causes test _should not allow -0 parsing it to 0_ to fail).

I could change the code to

    if ((needsToInvertSign ^ isNegative) || value === '-') {
        actualNumber *= -1;
        formatedValue = '-' + (!!actualNumber ? formatedValue : '');
    }

But then it allows the user to enter just the minus sign and then lose focus.

Maybe I could use the latter approach and clear the field if it only contains the minus sign.

What do you think?

**Comment by assisrafael** [comment]
The second approach will be better.

**Comment by brunobastosg** [comment]
@assisrafael, I implemented some new test cases. Also I had to change the existing test **'should not allow -0 parsing it to 0'**. I renamed it to **'should not allow -0 parsing it to - (just the minus sign)'** and changed its implementation a bit. Let me know if this is OK.

**Comment by assisrafael** [comment]
Thank you.

**Comment by brunobastosg** [comment]
@assisrafael, when will a new version with this feature be released?

**Pull request merged**
